### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by gbc8181** [sirfz/tesserocr#73] opened 2017-09-07 15:35 UTC
Hi everyone,

I tried to install tesserocr but always failed. It shows "error: command 'x86_64-linux-gnu-gcc' failed with exit status 1" I don't know why but I have installed tesseract 4.0 (tesseract works well). 
I got a result here every time:

Collecting tesserocr
  Downloading tesserocr-2.2.2.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 1.6MB/s 
Installing collected packages: tesserocr
  Running setup.py install for tesserocr ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-XTLf4W/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lGbZ3W-record/install-record.txt --single-version-externally-managed --compile:
    Supporting tesseract v4.00.00dev
    Configs from pkg-config: {'libraries': ['lept', 'tesseract'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}, 'library_dirs': ['/usr/local/lib'], 'include_dirs': ['/usr/local/include']}
    running install
    running build
    running build_ext
    building 'tesserocr' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/include -I/usr/include/python2.7 -c tesserocr.cpp -o build/temp.linux-x86_64-2.7/tesserocr.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from tesserocr.cpp:484:0:
    /usr/local/include/tesseract/unichar.h:164:10: error: ‘string’ does not name a type
       static string UTF32ToUTF8(const std::vector<char32>& str32);
              ^
    In file included from /usr/local/include/tesseract/osdetect.h:24:0,
                     from tesserocr.cpp:496:
    /usr/local/include/tesseract/unicharset.h:241:10: error: ‘string’ does not name a type
       static string CleanupString(const char* utf8_str) {
              ^
    /usr/local/include/tesseract/unicharset.h:244:10: error: ‘string’ does not name a type
       static string CleanupString(const char* utf8_str, int length);
              ^
    /usr/local/include/tesseract/unicharset.h: In member function ‘void UNICHARSET::unichar_insert_backwards_compatible(const char*)’:
    /usr/local/include/tesseract/unicharset.h:265:5: error: ‘string’ was not declared in this scope
         string cleaned = CleanupString(unichar_repr);
         ^
    /usr/local/include/tesseract/unicharset.h:265:5: note: suggested alternatives:
    In file included from /usr/include/c++/5/string:39:0,
                     from /usr/local/include/tesseract/unichar.h:25,
                     from tesserocr.cpp:484:
    /usr/include/c++/5/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
       typedef basic_string<char>    string;
                                     ^
    /usr/include/c++/5/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
    In file included from /usr/local/include/tesseract/osdetect.h:24:0,
                     from tesserocr.cpp:496:
    /usr/local/include/tesseract/unicharset.h:266:9: error: ‘cleaned’ was not declared in this scope
         if (cleaned != unichar_repr) {
             ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-XTLf4W/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lGbZ3W-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-XTLf4W/tesserocr/

**Comment by sirfz** [comment] 2017-09-07 16:31
Duplicate of #66. You can either install the package from master directly or set `CPPFLAGS=-DUSE_STD_NAMESPACE` environment variable before installing.

**Closed by sirfz** 2017-09-07 16:31 UTC
Labels: duplicate
