### ISSUE TITLE
pip install fails with tesseract/osdetect.h: No such file or directory

### ISSUE THREAD

**Issue by renjithamadeus** [sirfz/tesserocr#159] opened 2018-11-02 09:22 UTC
First of all, thank you for this great package, it has helped me very much.

I was trying to install tesseocr with tesseract v4 in docker container (Ubuntu 14)

Here is my docker file.

```
FROM python:3.6.5-stretch


RUN apt-get update && apt-get install -y \
    software-properties-common

RUN apt-get install --assume-yes git

RUN apt-get update && apt-get install -y\
    python3-pip \
    python3-dev

RUN add-apt-repository 'deb http://de.archive.ubuntu.com/ubuntu cosmic main universe'

RUN apt-get update && apt-get install -y --allow-unauthenticated\
    tesseract-ocr \
    libtesseract-dev \
    libleptonica-dev

COPY . /app
WORKDIR /app

RUN \
  mv .ssh ${HOME} && \
  chmod 0400 ${HOME}/.ssh/id_rsa

RUN python -m pip install --disable-pip-version-check --no-cache-dir -r requirements.txt

WORKDIR /app
```

I get the following error on building docker image
```
building 'tesserocr' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include -I/usr/local/include/python3.6m -c tesserocr.cpp -o build/temp.linux-x86_64-3.6/tesserocr.o -std=c++11 -DUSE_STD_NAMESPACE
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    tesserocr.cpp:673:32: fatal error: tesseract/osdetect.h: No such file or directory
     #include "tesseract/osdetect.h"
                                    ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```
**Edit**:
I see that a fix has been pushed for this (https://github.com/sirfz/tesserocr/pull/142).
May be this is not yet released yet?

**Comment by sirfz** [comment] 2018-11-02 17:22
duplicate of #129

**Closed by sirfz** 2018-11-02 17:22 UTC
Labels: duplicate
