### ISSUE TITLE
Build failed on Ubuntu

### ISSUE THREAD

**Issue by openedhardware** [sirfz/tesserocr#15] opened 2016-07-05 01:22 UTC
Hi, I am trying to install tesserocr on my Unbuntu x64 14.04.

Unfortunately, I failed to install tesserocr.
Here is the output:

ubuntu@ubuntu-MS:~/tmp/tesserocr$ sudo python setup.py build_ext -I/usr/local/include
running build_ext
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    test_suite='tests'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 970, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 846, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 82, in __init__
    _Command.__init__(self,dist)
  File "/usr/lib/python2.7/distutils/cmd.py", line 64, in __init__
    self.initialize_options()
  File "setup.py", line 120, in initialize_options
    build_args = package_config()
  File "setup.py", line 59, in package_config
    raise Exception(error)
Exception: Package tesseract was not found in the pkg-config search path.
Perhaps you should add the directory containing `tesseract.pc'
to the PKG_CONFIG_PATH environment variable
No package 'tesseract' found

Any idea?

**Comment by sirfz** [comment] 2016-07-05 20:44
According to the error, you don't seem to have tesseract installed on your system.  Try running the following command to check:

```bash
pkg-config --exists --print-errors tesseract
```
Make sure tesseract is installed as per the README file.

**Comment by openedhardware** [comment] 2016-07-08 00:02
Thanks for your reply, slrfz.

I have succeeded to install on my Ubuntu.

But unfortunately, I have failed to run file_to_text function.

/usr/bin/python2.7 /home/ubuntu/work/box_detect/text_extractor.py -i img/chefs_hat_Mrec.jpg -o img/output
Traceback (most recent call last):
  File "/home/ubuntu/work/box_detect/text_extractor.py", line 53, in <module>
    get_from_file(input_file_name)
  File "/home/ubuntu/work/box_detect/text_extractor.py", line 36, in get_from_file
    print(tesserocr.file_to_text(f_name))
  File "tesserocr.pyx", line 2326, in tesserocr.file_to_text (tesserocr.cpp:20745)
RuntimeError: Failed recognize picture

Any idea?

**Comment by sirfz** [comment] 2016-07-08 14:35
Have you tried a different image? Could you please share your code and image file so I can reproduce the issue?

**Comment by openedhardware** [comment] 2016-07-08 15:58
This is the code and image file.

    from PIL import Image
    from tesserocr import PyTessBaseAPI, RIL
    import argparse


    def extract_text(input_file_name, output_folder_name):
        image = Image.open(input_file_name)
        with PyTessBaseAPI() as api:
            api.SetImage(image)
            boxes = api.GetComponentImages(RIL.TEXTLINE, True)
            print 'Found {} textline image components.'.format(len(boxes))
            for i, (im, box, _, _) in enumerate(boxes):
                # im is a PIL image object
                # box is a dict with x, y, w and h keys
                api.SetRectangle(box['x'], box['y'], box['w'], box['h'])
                ocrResult = api.GetUTF8Text()
                conf = api.MeanTextConf()
                print (u"Box[{0}]: x={x}, y={y}, w={w}, h={h}, "
                       "confidence: {1}, text: {2}").format(i, conf, ocrResult, **box)




    if __name__ == '__main__':

        parser = argparse.ArgumentParser()
        parser.add_argument("-i", "--input_file_name", required=True, help="Input Image File Name")
        parser.add_argument("-o", "--output_folder_name", required=True, help="Output Folder Name")

        inst_arg = parser.parse_args()
        args = vars(inst_arg)

        input_file_name = args['input_file_name']
        output_folder_name = args['output_folder_name']

        extract_text(input_file_name, output_folder_name)
`

**Comment by sirfz** [comment] 2016-07-08 16:06
The code you posted has no call to the `file_to_text` function so it's irrelevant to the error in your prior post.

I tested your code and everything is fine:

```
$ python extract_text.py -i eurotext.tif -o .                                                                                         2 ↵
Found 12 textline image components.
Box[0]: x=105, y=66, w=718, h=47, confidence: 88, text: The (quick) [brown] {fox} jumps!


Box[1]: x=104, y=115, w=783, h=50, confidence: 90, text: Over the $43,456.78 <lazy> #90 dog


Box[2]: x=103, y=165, w=732, h=41, confidence: 90, text: & duck/goose, as 12.5% of E-mail


Box[3]: x=103, y=215, w=808, h=49, confidence: 88, text: from aspammer@website.com is spam.


Box[4]: x=102, y=266, w=775, h=48, confidence: 85, text: Der ,,schnelle” braune Fuchs springt


Box[5]: x=102, y=315, w=816, h=42, confidence: 86, text: ﬁber den faulen Hund. Le renard brun


Box[6]: x=101, y=366, w=732, h=43, confidence: 88, text: «rapide» saute par-dessus le chien


Box[7]: x=100, y=419, w=759, h=45, confidence: 88, text: paresseux. La volpe marrone rapida


Box[8]: x=100, y=466, w=734, h=45, confidence: 90, text: salta sopra i] cane pigro. El zorro


Box[9]: x=99, y=516, w=734, h=47, confidence: 86, text: marrén répido salta sobre el perro


Box[10]: x=98, y=568, w=731, h=45, confidence: 87, text: perezoso. A raposa marrom répida


Box[11]: x=98, y=616, w=612, h=45, confidence: 82, text: salta sobre 0 C50 preguieoso.
```

**Comment by openedhardware** [comment] 2016-07-08 16:08
Can you send me the image file?
Seems like my image is the reason...
My email address is wester.de.weerdt@dutchmail.com.
Thanks.

**Comment by sirfz** [comment] 2016-07-08 16:12
Sure, it's [eurotext.tif](https://github.com/sirfz/tesserocr/blob/master/tests/eurotext.tif?raw=true) from the tests/ directory.

**Comment by sirfz** [comment] 2016-07-08 16:13
I'm closing this issue since it diverted from it's original subject. If you need to follow this further, feel free to open a new issue :)

**Closed by sirfz** 2016-07-08 16:13 UTC
