### ISSUE TITLE
Error while performing OCR on image

### ISSUE THREAD

**Issue by jorgeflorez** [sirfz/tesserocr#55] opened 2017-06-06 22:02 UTC
Hello, 
I am using the following code in order to perform OCR on an image (attached):

```python
from tesserocr import PyTessBaseAPI
from PIL import Image

DEFAULT_LANGUAGE = "spa"
filePath = "/home/jorge/Desktop/prueba_tess/c1.png"

if __name__ == '__main__':
    img = Image.open(filePath)
    tesseract = PyTessBaseAPI(lang=DEFAULT_LANGUAGE)
    tesseract.SetImage(img)
    tesseract.Recognize()
    print tesseract.GetUTF8Text()
    tesseract.End()
```

but what I am getting with this particular image in console is the following:
`start >= 0 && start + num <= length_:Error:Assert failed:in file ratngs.cpp, line 321`

Here is what I am using 
tesserocr 2.2.1
tesseract 3.04.01
leptonica-1.71
libjpeg 8d : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8

I think I have all correctly set up because I have extracted text from other images. but with this one throws that "error"...
Any help is appreciated.
Thanks in advance!
![c1](https://user-images.githubusercontent.com/23032523/26853851-44fb9234-4ad9-11e7-99ce-1cd67d8e9751.png)

**Comment by sirfz** [comment] 2017-06-07 19:09
It seems the problem is coming from PIL, if you use `SetImageFile(file)` method to load the image into tesseract it works normally but if you use `SetImage(Image.load(file))` as in your example, the program crashes. I verified this by saving the image using `Image.save` after loading it in PIL and then use `SetImageFile` on that file which similarly crashed the program.

Here's an example to reproduce this:

```python
In [1]: import tesserocr

In [2]: from PIL import Image

In [3]: tesserocr.__version__
Out[3]: '2.2.1'

In [4]: print tesserocr.tesseract_version()
tesseract 3.05.00
 leptonica-1.74
  libjpeg 8d (libjpeg-turbo 1.5.0) : libpng 1.6.28 : libtiff 4.0.7 : zlib 1.2.11


In [5]: api = tesserocr.PyTessBaseAPI(lang='spa')

In [6]: api.SetImageFile('Downloads/26853851-44fb9234-4ad9-11e7-99ce-1cd67d8e9751.png')

In [7]: api.Recognize() # works
Out[7]: True

In [8]: image = Image.open('Downloads/26853851-44fb9234-4ad9-11e7-99ce-1cd67d8e9751.png')

In [9]: image.save('pil_saved.png')

In [10]: api.SetImageFile('pil_saved.png')

In [11]: api.Recognize() # crashes
start >= 0 && start + num <= length_:Error:Assert failed:in file ratngs.cpp, line 321
[1]    10774 segmentation fault (core dumped)  ipython
```

Interestingly, the following works just fine:

```python
In [11]: api.SetVariable("tessedit_create_txt", "1")
Out[11]: True

In [12]: api.ProcessPages('example', 'pil_saved.png')
Out[12]: True
```
Which generates `example.txt` containing the text from the image (mostly garbage in this case).

I was going to suggest reporting this to the [Pillow](https://github.com/python-pillow/Pillow) team.  However, since the example in the 2nd approach worked, it means this is a corner case that may be fixed in tesseract so I suggest you first report this to the [tesseract](https://github.com/tesseract-ocr/tesseract) team instead.

Note that I also tried it with tesseract v3.05.01 and leptonica 1.74.1 which has the same issue.

**Comment by jorgeflorez** [comment] 2017-06-12 02:54
Hello sirfz,
thank you for your detailed reply (I apologize for not answering before :) ). Indeed, this is a very "peculiar" case.
When I use my python program, it fails. but when I use the command line, it works!

![command](https://user-images.githubusercontent.com/23032523/27017701-0bd1f9ba-4ef0-11e7-92bc-fb7e501e3210.png)

Anyway, I will report this to the Tesseract team, maybe something can be done. By the way, I have another image with the opposite problem. It fails in the command line but when using the python program it works! (if you think it is worth checking this out, I will attach it).
Thanks.

**Comment by sirfz** [comment] 2017-06-12 17:03
I would like to try out the opposite-case image if you don't mind sharing it. I also think it would be helpful for the tesseract team if you include it in your report to them (which I hope you can link to here so I, and others, can follow up).

**Comment by jorgeflorez** [comment] 2017-06-12 17:46
hi,
here it is the other image:
![c2](https://user-images.githubusercontent.com/23032523/27046598-b0e189d2-4f6a-11e7-825d-dedabc4c809f.png)
The following image shows the outcome of my program:
![outcome2](https://user-images.githubusercontent.com/23032523/27046830-839f6f60-4f6b-11e7-8737-d90b8e973f94.png)

When I use the command I get this:
![outcome3](https://user-images.githubusercontent.com/23032523/27046902-c9f70a18-4f6b-11e7-9fb7-9f530a0380ea.png)
At first, I thought that tesseract had failed and the result file had nothing (because ot the messages in the window) . But I just checked and the file contains some text at the bottom.
[output2.txt](https://github.com/sirfz/tesserocr/files/1069027/output2.txt)
It seems that there are a lot more text in the file than in the console. It should show both sides the same text, right?
I will report the issue to the Tesseract team (not sure what should I write) and then I will put the link here.

**Comment by jorgeflorez** [comment] 2017-06-17 00:26
Hi, this is the link to the [issue](https://github.com/tesseract-ocr/tesseract/issues/989). I created it some days ago, but no one has said anything. Anyway, the workaround you gave me will suffice. Thank you!

**Comment by sirfz** [comment] 2017-06-17 20:09
Hi @jorgeflorez, regarding your second image, use `tesseract -l spa image.png stdout` to print the result to stdout instead of a file. I had similar results as you.

Another thing to note is that Pillow seems to apply some kind of pre-processing to the image after loading it since the resulting image is not identical to the original. It might be worth bringing this up with the Pillow team.

In your case, if you wish to only get the output of `GetUTF8Text`, it works fine as long as you don't call `Recognize` which is not required in this case (and which is crashing your program).

**Closed** 2017-06-20 16:17 UTC

**Comment by sirfz** [comment] 2017-06-20 16:19
@jorgeflorez, just pushed a fix into the master branch. Try it out, the API should no longer crash on `Recognize`. In addition, you can now pass a timeout parameter to the method call to indicate a timeout in milliseconds (e.g. `api.Recognize(timeout=5000)` will return `False` if recognition doesn't complete within 5 seconds).

**Comment by jorgeflorez** [comment] 2017-06-20 16:30
Hi sirfz,
thank you for your effort on this. I use tesserocr to get not just the text, but also the coordinates for each of the words I find.
I will try to use the master branch and test again. Thanks again for your help :)
